module.exports = [
  "¡Aprender ${texto}! Vaya, alguien sí tiene aspiraciones antes de morir.",
  "Interesante elección eso de ${texto}, espero que tu talento supere tus ilusiones.",
  "No sé si el mundo necesite otro más queriendo ${texto}, pero al menos lo intentas.",
  "Mira qué lindo, alguien tiene un propósito. ¿Te dolió mucho decidirte por ${texto}?",
  "¡Ey, qué decente propósito tienes con ${texto}! Ya era hora, carajo.",
  "¿Quieres ${texto}? Por lo menos alguien aquí tiene ideas propias, felicidades.",
  "Felicidades, tu propósito de ${texto} te salva de la absoluta mediocridad, por ahora.",
  "Por fin alguien con propósito, aunque sea ${texto}. Te apoyo en tu locura.",
  "Tu propósito es ${texto}, genial. Espero que la vida no te decepcione demasiado.",
  "Elegiste ${texto}, buena decisión; ya veremos cuánto te dura esa motivación.",
  "Tienes potencial, especialmente porque elegiste ${texto} y no ‘ver Netflix hasta morir’.",
  "Muy bien, tu plan de ${texto} es menos lamentable de lo que esperaba.",
  "Finalmente alguien con una meta concreta como ${texto}, qué raro.",
  "Ah, el propósito de ${texto}, ambicioso. Solo recuerda: llorar está permitido.",
  "Mis felicitaciones, escogiste ${texto} y no la mediocridad eterna.",
  "Wow, alguien con sueños reales (${texto}), ya casi devuelves mi fe en la humanidad.",
  "Con ese propósito de ${texto}, hasta podría fingir entusiasmo por ti.",
  "Bravo, tienes un propósito como ${texto}; no dejes que la vida te aplaste demasiado rápido.",
  "Tu propósito es ${texto}, aceptable. Ahora, a ver cuánto tiempo te dura.",
  "Mira nada más, alguien aquí sabe tomar decisiones (${texto}), raro pero agradable.",
  "Oh, elegiste ${texto}. Por fin una respuesta decente entre tanto inútil.",
  "Tener el propósito de ${texto} es algo respetable; espero que no te arrepientas.",
  "¡Qué lindo propósito (${texto})! Solo te falta talento, pero es un detalle menor.",
  "Decir ${texto} es bastante valiente viniendo de alguien como tú, me agrada.",
  "¡Vaya! Alguien tiene claro su propósito (${texto}). ¿Puedo llorar de alegría?",
  "Admitir que quieres ${texto} demuestra madurez, aunque sea accidental.",
  "Tu propósito (${texto}) tiene mi aprobación, disfrútala antes de que cambie de opinión.",
  "Interesante propósito (${texto}), espero que no sea solo para quedar bien conmigo.",
  "Veo potencial en tu propósito (${texto}). Sí, lo digo en serio... casi.",
  "Buen propósito: ${texto}. Intenta mantenerlo más de una semana, por favor.",
];
