module.exports = [
  "¡Uy, alguien despertó hormonal hoy! ¿Tu propósito es siempre hablar así de mierda?",
  "Vaya, qué forma tan elegante de decir que no tienes propósito, ${texto}.",
  "Te salió lo cavernícola, tranquilo, nadie esperaba que tuvieras propósito.",
  "Ah, entiendo, tu propósito es escupir groserías como ${texto}. Excelente plan de vida.",
  "¿Con esa boquita buscas propósito, o solo atención porque no te abrazaron de niño?",
  "Relájate, Tarantino frustrado, solo preguntaba por tu propósito, no por tu vida sexual.",
  "Qué lindo, insultas porque tu propósito es no saber expresarte mejor, ¿cierto?",
  "Tu educación tiene menos propósito que tus insultos baratos.",
  "¿Tu propósito es ser un imbécil siempre, o hoy es ocasión especial?",
  "¿Te dieron permiso en casa para hablar así, o encontraste solito tu falta de propósito?",
  "Tranquilo, malote, ya nos quedó claro que tu propósito es hacer el ridículo.",
  "Tu mamá debe estar orgullosa del propósito que tienes para contestar así, ${texto}.",
  "Si tu mejor respuesta es ${texto}, mejor ni te esfuerces en buscar propósito.",
  "Interesante propósito ese de insultar; imagino que eso llena tu vacío existencial, ¿no?",
  "¿Ese vocabulario es parte de tu falta de propósito, o simplemente nunca abriste un libro?",
  "Tienes menos clase que propósito, y eso ya es decir bastante.",
  "Propósito: hablar basura. Estado: cumplido con honores, ${texto}.",
  "No te preocupes, todos necesitamos un ejemplo de lo que pasa al vivir sin propósito.",
  "Si tu propósito es hablar como idiota, entonces felicidades: lo lograste.",
  "Gracias por aclarar con ${texto} que tu propósito es ser insoportable, sigue así.",
  "Veo que tu propósito es competir en quién dice más pendejadas por minuto, vas ganando.",
  "¿Tu grosería es parte de tu encanto natural, o la única habilidad que tienes?",
  "Ah, sí, la clásica respuesta de quien tiene el propósito de fracasar en todo.",
  "Tu respuesta (${texto}) tiene menos nivel que un reggaetón escrito por monos ebrios.",
  "Felicidades, tu propósito en la vida es hacer que todos prefieran ignorarte.",
  "¿Te duele el orgullo o es que nunca tuviste propósito y eso te enoja?",
  "Te recomiendo un propósito: aprender a hablar como adulto funcional.",
  "Insultar no es propósito, es simplemente admitir que no tienes argumentos.",
  "¿Hablas así por elección o porque ningún otro propósito te aceptó?",
  "Con respuestas así (${texto}), mejor vete buscando propósito en otro planeta.",
];
