module.exports = [
  "¡Ah, mira! Un propósito tan mierda como ${texto}, qué inesperado.",
  "Propósito no encontrado, ¿probaste buscarte una vida primero?",
  "Tu propósito es ${texto}? Wow, ¿cómo logras vivir contigo mismo?",
  "Menos propósito tienes tú que una bolsa de basura reciclable.",
  "Si tu plan es no tener propósito, al menos sé honesto y asúmelo.",
  "Con esa meta de ${texto}, ¿no te da vergüenza existir?",
  "¿No tienes propósito? Felicidades, lograste decepcionarme aún más.",
  "Tu propósito es ${texto}, y tu futuro está más negro que tu autoestima.",
  "¿Vas por la vida sin rumbo? Qué novedad, me impactas con tu originalidad.",
  "Elegiste ${texto}? Mis condolencias a quienes te conozcan.",
  "Ni las cucarachas tienen tan poco propósito como tú.",
  "Felicidades por tu propósito inexistente, qué ganas de perder oxígeno.",
  "¿En serio tu propósito es ${texto}? Mejor devuélvete al útero y reinicia.",
  "¡Atención! Aquí tenemos al ganador del premio al propósito más estúpido.",
  "Vaya, otro genio cuyo propósito es no tener uno. Nunca antes visto.",
  "Con ese propósito de ${texto}, estás listo para protagonizar tu propio fracaso.",
  "Dices no tener propósito como si fuera algo de lo que sentirse orgulloso, patético.",
  "¿Te duele la cabeza de tanto pensar en nada, genio?",
  "Wow, tu propósito es ${texto}? Dime más, así me duermo rápido.",
  "Ser inútil no es un propósito, deja de presumirlo tanto.",
  "El premio al propósito más triste va para ti, obvio.",
  "Tu vida es un error tipográfico que olvidaron corregir.",
  "Si tu propósito es ${texto}, reconsidera el suicidio profesional como opción.",
  "Tienes menos dirección en la vida que una brújula en el culo.",
  "Vivir sin propósito es una mierda, pero tú lo haces ver como arte.",
  "Que tu propósito sea ${texto} debería considerarse crimen ecológico.",
  "Si no tienes propósito, al menos no molestes a quienes sí lo tienen.",
  "Eres como el Internet Explorer de las personas: lento y sin propósito alguno.",
  "Con ${texto} como propósito, no sorprende que la evolución te haya ignorado.",
  "Vivir sin propósito debería darte descuento en terapia."
];
